functional:
  - Пользователь должен иметь возможность создавать учетные записи, предоставляя необходимые данные (например, имя, адрес электронной почты, пароль).
  - Пользователи должны иметь возможность входить в систему, используя свои учетные данные.
  - Пользователь должен иметь возможность создавать соревнования и присоединятся к существующим
  - Пользователь должен иметь возможность выбирать сложность игры( от легкого жо сложного), тип игры( с др. пользователем, с другом, с ботом).
  - Пользователь должен иметь возможность выбирать длительность игры
  - Пользователь должен иметь возможность выбирать задание по имени или тегам.
  - Пользователь должен иметь возможность писать и редактировать код в игре
  - Пользователь должен иметь возможность отправлять решение на проверку
  - Система должна иметь возможность предоставлять задачи для решения.
  - Система должна иметь возможность автоматически проверять задания на правильность решения
  - Система должна иметь возможность предоставлять результаты проверки задач.
  - Пользователь должен иметь возможность общаться с участниками соревнований
  - Пользователь должен иметь возможность видеть рейтинг и турнирную таблицу по результатам игры пользователей
  - Пользователь должен иметь возможность выбирать разные языки программирования
  - Система должна иметь возможность определять победителя и проигравшего.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Пользователь должен иметь возможность участвовать в нескольких играх
implicit:
  - Интерфейс сайта должен быть простым в использовании
  - Пользователь должен иметь возможность получать обратную связь и помощь
  - Интерфейс сайта должен иметь возможность поддерживать русский язык.
