functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователи должны иметь возможность входить в систему, используя свои учетные данные.
  - Пользователь должен иметь возможность создавать группу игроков.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - 
