functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте.
  - Пользователи должны иметь возможность входить в систему, используя свои учетные данные.
  - Пользователь должен иметь возможность создавать соревнования и присоединятся к существующим
  - Пользователь должен иметь возможность выбирать сложность игры, тип игры.
  - Пользователь должен иметь возможность выбирать длительность игры
  - Пользователь должен иметь возможность выбирать задание по имени или тегам.
  - Пользователь должен иметь возможность писать и редактировать код в игре
  - Пользователь должен иметь возможность отправлять решение на проверку
  - Система должна иметь возможность предоставлять задачи для решения.
  - Система должна иметь возможность автоматически проверять задания (корректность и правильность решения)
  - Система должна иметь возможность предоставлять результаты проверки задач.
  - Пользователь должен иметь возможность общаться с участниками соревнований
  - Пользователь должен иметь возможность видеть рейтинг и статистику по результатам игры пользователей
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Интерфейс сайта должен быть простым в использовании
  - Пользователь должен иметь вохможность выбирать разные языки программирования
  - Пользователь должен иметь возможность получать обратную связь и помощь

